# -*- coding: utf-8 -*-
"""1-5array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10g8qcMI1MnvhAkbID8LzCndqGTWtFHz1
"""



import numpy as np
# Creating an array from a list
array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)
# Creating an array with a range of values
array_with_range = np.arange(10)
print("Array with range:", array_with_range)
# Creating an array of zeros
zeros_array = np.zeros((3, 3))
print("Array of zeros:\n", zeros_array)
# Creating an array of ones
ones_array = np.ones((2, 5))
print("Array of ones:\n", ones_array)

import numpy as np
# Creating arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Element-wise addition
add_result = np.add(a, b)
print("Addition:", add_result)
# Element-wise subtraction
sub_result = np.subtract(a, b)
print("Subtraction:", sub_result)
# Element-wise multiplication
mul_result = np.multiply(a, b)
print("Multiplication:", mul_result)
# Element-wise division
div_result = np.divide(a, b)
print("Division:", div_result)

import numpy as np
# Creating a 1D array
array = np.arange(12)
print("Original array:", array)
# Reshaping to 2D array (3x4)
reshaped_array = array.reshape((3, 4))
print("Reshaped to 3x4:\n", reshaped_array)
# Reshaping to 3D array (2x3x2)
reshaped_array_3d = array.reshape((2, 3, 2))
print("Reshaped to 2x3x2:\n", reshaped_array_3d)

import numpy as np
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", array_2d)
# Accessing element at (1, 2)
element = array_2d[1, 2]
print("Element at (1, 2):", element)
# Slicing a subarray (rows 1 to 2, columns 0 to 1)
subarray = array_2d[1:3, 0:2]
print("Sliced subarray:\n", subarray)
# Accessing a column (all rows, column 1)
column = array_2d[:, 1]
print("Column 1:", column)

import numpy as np
# Creating an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Calculating mean
mean = np.mean(array)
print("Mean:", mean)
# Calculating median
median = np.median(array)
print("Median:", median)
# Calculating standard deviation
std_dev = np.std(array)
print("Standard Deviation:", std_dev)
# Finding minimum and maximum values
min_val = np.min(array)
max_val = np.max(array)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

import numpy as np
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_product = matrix1 * matrix2
matrix_divide = matrix1 / matrix2
matrix_multiply = np.dot(matrix1, matrix2)
matrix1_transpose = np.transpose(matrix1)
diagonal_sum = np.trace(matrix1)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Sum:\n", matrix_sum)
print("Matrix Difference:\n", matrix_diff)
print("Matrix Element-wise Product:\n", matrix_product)
print("Matrix Element-wise Division:\n", matrix_divide)
print("Matrix Multiplication:\n", matrix_multiply)
print("Transpose of Matrix 1:\n", matrix1_transpose)
print("Sum of Diagonal Elements of Matrix 1:", diagonal_sum)

import numpy as np;
X = np.array([[1, 2],
[3, 4]])
Y = np.array([[5,6], [7,8]])
print("Matrix X is :\n ",X)
print("Matrix Y is : \n",Y)
a=np.power(X,2)
print("X^2=",a)
result = a + 2 * Y
print("X^2+2*Y is \n ",result)

import numpy as np
two_dimensional_array = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12],
 [13, 14, 15, 16]])
excluding_first_row = two_dimensional_array[1:]
excluding_last_column = two_dimensional_array[:, :-1]
column_1_2_in_row_2_3 = two_dimensional_array[1:3, 0:2]
column_2_3 = two_dimensional_array[:, 1:3]
elements_2_3_in_first_row = two_dimensional_array[0, 1:3]
descending_order = two_dimensional_array.ravel()[::-1][4:11]
print("Original 2D array:\n", two_dimensional_array)
print("Elements excluding the first row:\n", excluding_first_row)
print("Elements excluding the last column:\n", excluding_last_column)
print("Elements of the 1st and 2nd column in the 2nd and 3rd row:\n",
column_1_2_in_row_2_3)
print("Elements of the 2nd and 3rd column:\n", column_2_3)
print("2nd and 3rd element of the 1st row:\n", elements_2_3_in_first_row)
print("Elements from indices 4 to 10 in descending order:\n", descending_order)

import numpy as np
A = np.array([[2, 1,-2],[3,0,1],[1,1,-1]])
b = np.array([-3,5,-2])
X = np.linalg.solve(A, b)
print("Matrix A:")
print(A)
print("Vector b:")
print(b)
print("Solution for X:")
print(X)

